import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from '../components/Sidebar';
import { ThemeProvider } from '../components/ThemeProvider'

export const dynamic = 'force-dynamic';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-row bg-gray-100 dark:bg-gray-900 dark:text-white">
        <ThemeProvider>
          <aside className="flex flex-1">
            <Sidebar />
          </aside>
          <main className="flex-4 py-4 pr-4 rounded-2xl overflow-auto ">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}